package worker

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/luckydiss/studlance_ai/internal/httpapi"
	"github.com/luckydiss/studlance_ai/internal/id"
	"github.com/luckydiss/studlance_ai/internal/worker/agents"
	"github.com/luckydiss/studlance_ai/internal/worker/client"
	"github.com/luckydiss/studlance_ai/internal/worker/procwin"
	"github.com/luckydiss/studlance_ai/prompts"
)

// agentForStage maps stages to their CLI agent.
func agentForStage(stage string) string {
	if stage == "draft" {
		return "codex"
	}
	return "claude"
}

// runStage executes one stage attempt: prompt, agent run, run reporting and
// the question check (05-worker.md «Этапы», «После этапа»).
func (j *jobExec) runStage(ctx, agentCtx context.Context, stage, action string) stageResult {
	agent := agentForStage(stage)

	// A cancellation confirmed before the stage must not start any new work:
	// no revision preparation, no uploads, no agent process.
	if j.cancelRequested.Load() {
		return stageResult{outcome: outcomeCanceled}
	}

	// Revision prep runs on any revise-stage action (revise, but also a
	// continue/answer after a crash mid-prep) and is idempotent.
	if stage == "revise" {
		if err := j.prepareRevision(j.activeCtx(ctx)); err != nil {
			if isStale(err) {
				return stageResult{outcome: outcomeAborted}
			}
			if errors.Is(err, errCanceled) {
				return stageResult{outcome: outcomeCanceled}
			}
			return stageResult{outcome: outcomeFailed, errText: "не удалось подготовить доработку: " + err.Error()}
		}
	}

	session := j.sessionFor(agent)
	resume := false
	switch action {
	case "continue", "answer", "revise":
		resume = session != ""
	}

	// A fresh claude session id (UUID v4) is generated by the worker, recorded
	// locally and posted before launch (05-worker.md «Этапы»). The expected
	// session is always the one the process is launched with.
	if agent == "claude" && !resume {
		session = id.NewV4()
		j.setSession(agent, session)
		if err := j.setState(j.serviceCtx(ctx), map[string]interface{}{"claude_session_id": session}); err != nil {
			if isStale(err) {
				return stageResult{outcome: outcomeAborted}
			}
			j.log.Error("post session", "err", err)
		}
	}

	prompt, err := j.buildPrompt(stage, action, resume)
	if err != nil {
		return stageResult{outcome: outcomeFailed, errText: "не удалось собрать промпт: " + err.Error()}
	}

	createReq := httpapi.CreateRunRequest{
		Agent:   httpapi.CreateRunRequestAgent(agent),
		Attempt: j.asn.Attempt,
		Epoch:   j.asn.Epoch,
		Stage:   httpapi.CreateRunRequestStage(stage),
		Version: j.asn.Version,
	}
	if agent == "claude" && session != "" {
		createReq.SessionId = &session
	}
	runID, err := j.w.cl.CreateRun(j.activeCtx(ctx), j.asn.JobId, createReq)
	if err != nil {
		if isStale(err) || isConflict(err) {
			return stageResult{outcome: outcomeAborted}
		}
		return stageResult{outcome: outcomeFailed, errText: "не удалось создать запуск: " + err.Error()}
	}
	log := j.log.With("run", runID, "agent", agent, "stage", stage, "action", action)

	// QUESTIONS.md fingerprint before the run (created or changed ⇒ question).
	qPath := filepath.Join(j.dir, "QUESTIONS.md")
	qBefore := fileFingerprint(qPath)

	// The stage timeout counts from the persisted stage start (state.json):
	// a continue after a worker restart does NOT restart the clock. A fresh
	// stage (start/revise) and an answer delivery reset it (03-lifecycle.md).
	if action != "continue" || j.state.StageStartedAt.IsZero() {
		j.state.StageStartedAt = j.w.now()
		j.saveState()
	}
	stageDur := j.w.cfg.StageDuration()
	remaining := stageDur - j.w.now().Sub(j.state.StageStartedAt)
	if remaining < 0 {
		remaining = 0
	}
	runCtx, cancelRun := context.WithCancel(agentCtx)
	defer cancelRun()
	timer := time.AfterFunc(remaining, func() {
		j.stageTimeout.Store(true)
		cancelRun()
	})
	defer timer.Stop()

	// COM-launched Office/КОМПАС processes live outside the agent tree: kill
	// the ones started during THIS stage.
	officeBefore := procwin.OfficePIDs()
	defer procwin.KillNewOffice(officeBefore)

	args := j.agentArgs(agent, session, resume)
	res, runErr := j.runAgent(ctx, runCtx, log, runID, agent, session, args, prompt)

	// Report the run before any lifecycle transition: after finish/question
	// the lease is gone and epoch'd writes would be rejected.
	j.reportRun(ctx, log, runID, res, runErr)

	switch {
	case j.stale.Load() || errors.Is(runErr, client.ErrStaleLease):
		return stageResult{outcome: outcomeAborted}
	case ctx.Err() != nil:
		// Worker shutdown (Ctrl+C): no finish — the server reclaims the order
		// and hands it back as continue.
		return stageResult{outcome: outcomeAborted}
	case j.cancelRequested.Load():
		j.patchRunOutcome(ctx, runID, res, httpapi.PatchRunRequestOutcomeCanceled, "")
		return stageResult{outcome: outcomeCanceled}
	case j.stageTimeout.Load():
		errText := fmt.Sprintf("превышен таймаут этапа %s", humanDuration(stageDur))
		j.patchRunOutcome(ctx, runID, res, httpapi.PatchRunRequestOutcomeTimeout, errText)
		return stageResult{outcome: outcomeFailed, timeout: true, errText: errText}
	}

	if q := questionText(qPath, qBefore); q != "" {
		// PATCH the run before the question: POST /question drops the lease.
		j.patchRunOutcome(ctx, runID, res, httpapi.PatchRunRequestOutcomeQuestion, "")
		if err := j.postQuestion(ctx, runID, q); err != nil {
			if isStale(err) {
				return stageResult{outcome: outcomeAborted}
			}
			return stageResult{outcome: outcomeFailed, errText: "не удалось задать вопрос: " + err.Error()}
		}
		return stageResult{outcome: outcomeQuestion}
	}

	fail := func(errText string) stageResult {
		j.patchRunOutcome(ctx, runID, res, httpapi.PatchRunRequestOutcomeFailed, errText)
		return stageResult{outcome: outcomeFailed, errText: errText}
	}
	if runErr != nil {
		return fail("запуск агента: " + runErr.Error())
	}
	if res.ExitCode != 0 {
		return fail(fmt.Sprintf("%s завершился с кодом %d", agent, res.ExitCode))
	}
	if res.AgentFailed != "" {
		return fail(res.AgentFailed)
	}
	if _, err := j.readManifest(); err != nil {
		return fail(err.Error())
	}
	j.patchRunOutcome(ctx, runID, res, httpapi.PatchRunRequestOutcomeOk, "")
	return stageResult{outcome: outcomeSuccess}
}

// runAgent starts the agent process and streams its trace to the server.
// jobCtx covers server calls (session posts), runCtx the agent process.
// expectSession is the session the process is launched with (claude init check).
func (j *jobExec) runAgent(jobCtx, runCtx context.Context, log *slog.Logger, runID, agent, session string, args []string, prompt string) (agents.Result, error) {
	cmdCfg := j.w.cfg.Codex
	if agent == "claude" {
		cmdCfg = j.w.cfg.Claude
	}
	expectSession := ""
	if agent == "claude" {
		expectSession = session
	}
	spec := agents.RunSpec{
		Agent:         agent,
		Command:       cmdCfg.Command,
		Args:          args,
		Dir:           j.dir,
		Prompt:        prompt,
		LogPath:       filepath.Join(j.logsDir(), runID+".jsonl"),
		ExpectSession: expectSession,
		Send: func(steps []agents.NewStep) error {
			batch := make([]httpapi.NewTraceStep, 0, len(steps))
			for _, s := range steps {
				ns := httpapi.NewTraceStep{Seq: s.Seq, Ts: s.Ts, Type: s.Type, Summary: s.Summary}
				if s.Payload != nil {
					ns.Payload = &s.Payload
				}
				batch = append(batch, ns)
			}
			if err := j.w.cl.AppendSteps(j.activeCtx(jobCtx), j.asn.JobId, runID, j.asn.Epoch, batch); err != nil {
				if isStale(err) {
					j.stale.Store(true)
					j.stopWork()
				}
				return err
			}
			return nil
		},
		OnSession: func(id string) {
			j.setSession(agent, id)
			key := "codex_thread_id"
			if agent == "claude" {
				key = "claude_session_id"
			}
			if err := j.setState(j.serviceCtx(jobCtx), map[string]interface{}{key: id}); err != nil {
				log.Error("post session id", "err", err)
			}
		},
	}
	return agents.Run(runCtx, spec)
}

// reportRun uploads the raw log and patches the run row with the outcome
// fields known so far (tokens, cost, exit code). It is a service report: the
// log upload is not work that a cancellation should silently drop.
func (j *jobExec) reportRun(ctx context.Context, log *slog.Logger, runID string, res agents.Result, runErr error) {
	if j.stale.Load() {
		return
	}
	cctx := j.serviceCtx(ctx)
	logPath := filepath.Join(j.logsDir(), runID+".jsonl")
	if _, err := os.Stat(logPath); err == nil {
		if err := j.putWithRetry(cctx, logPath, func(r io.Reader) error {
			return j.w.cl.PutRunLog(cctx, j.asn.JobId, runID, j.asn.Epoch, r)
		}); err != nil {
			log.Error("upload log", "err", err)
		}
	}
	j.patchRunOutcome(ctx, runID, res, "", "")
	if runErr != nil && !errors.Is(runErr, context.Canceled) {
		log.Error("agent run", "err", runErr)
	}
}

// patchRunOutcome sends PATCH /runs/{run_id}; outcome "" keeps the outcome unset.
// It is a service request (it reports the terminal state of the run), so it
// runs on the service context and keeps its retries after a cancellation.
func (j *jobExec) patchRunOutcome(ctx context.Context, runID string, res agents.Result, outcome httpapi.PatchRunRequestOutcome, errText string) {
	if j.stale.Load() {
		return
	}
	now := j.w.now()
	req := httpapi.PatchRunRequest{
		Epoch:        j.asn.Epoch,
		ExitCode:     &res.ExitCode,
		FinishedAt:   &now,
		InputTokens:  &res.Usage.InputTokens,
		OutputTokens: &res.Usage.OutputTokens,
	}
	if res.Usage.CostUSD > 0 {
		cost := float32(res.Usage.CostUSD)
		req.CostUsd = &cost
	}
	if outcome != "" {
		req.Outcome = &outcome
	}
	if errText != "" {
		req.Error = &errText
	}
	if err := j.w.cl.PatchRun(j.serviceCtx(ctx), j.asn.JobId, runID, req); err != nil {
		if isStale(err) {
			j.stale.Store(true)
			j.stopWork()
		}
		j.log.Error("patch run", "err", err)
	}
}

// postQuestion moves QUESTIONS.md aside and posts the question (needs_input).
func (j *jobExec) postQuestion(ctx context.Context, runID, text string) error {
	j.state.QuestionSeq++
	_ = os.MkdirAll(j.questionsDir(), 0o755)
	dst := filepath.Join(j.questionsDir(), fmt.Sprintf("q-%d.md", j.state.QuestionSeq))
	if err := os.Rename(filepath.Join(j.dir, "QUESTIONS.md"), dst); err != nil {
		// Cross-device or locked file: copy + remove.
		if raw, rerr := os.ReadFile(filepath.Join(j.dir, "QUESTIONS.md")); rerr == nil {
			_ = os.WriteFile(dst, raw, 0o644)
			_ = os.Remove(filepath.Join(j.dir, "QUESTIONS.md"))
		}
	}
	j.saveState()
	return j.w.cl.Question(j.serviceCtx(ctx), j.asn.JobId, j.asn.Epoch, text)
}

// buildPrompt renders the stage prompt (06-prompts.md).
//
// A run without a known session (start, continue/answer right after a worker
// restart, revise without the claude session) always gets the full stage
// prompt: the common block, the client's request, the local file names and
// the stage instructions. Only a session resume keeps the short prompt
// (continue, answer, revise). The «Предыдущая попытка не завершилась…» block
// is added on start with attempt ≥ 1 and on continue/answer without a session.
func (j *jobExec) buildPrompt(stage, action string, resume bool) (string, error) {
	vars := prompts.Vars{
		Prompt: j.asn.Prompt,
		Files:  j.filesLine(),
		Retry: (action == "start" && j.asn.Attempt >= 1) ||
			((action == "continue" || action == "answer") && !resume),
	}
	// full selects the standalone stage template (dialogue-independent); the
	// short revise template is used only when the claude session is resumed.
	stagePrompt := func(full bool) (string, error) {
		switch stage {
		case "revise":
			vars.Version = j.asn.Version
			vars.PrevVersion = j.asn.Version - 1
			vars.RevisionFile = fmt.Sprintf("REVISION-%d.md", j.asn.Version)
			if full {
				return prompts.Render("revise_full", vars)
			}
			return prompts.Render("revise", vars)
		case "verify":
			return prompts.Render("verify", vars)
		default:
			return prompts.Render("draft", vars)
		}
	}
	switch {
	case action == "continue" && resume:
		return prompts.Render("continue", vars)
	case action == "answer" && resume:
		if j.asn.Answer != nil {
			vars.Answer = *j.asn.Answer
		}
		return prompts.Render("answer", vars)
	case action == "revise" && resume:
		// The claude session is known: the short revise prompt is enough.
		return stagePrompt(false)
	case action == "answer":
		// No session to resume: full stage prompt plus the client's answer.
		p, err := stagePrompt(true)
		if err != nil {
			return "", err
		}
		answer := ""
		if j.asn.Answer != nil {
			answer = *j.asn.Answer
		}
		return p + "\n\nСтудент ответил на вопрос: " + answer + "\n", nil
	default:
		return stagePrompt(true)
	}
}

// agentArgs builds the CLI argv (ARCHITECTURE.md «Запуск CLI»).
func (j *jobExec) agentArgs(agent, session string, resume bool) []string {
	if agent == "codex" {
		if resume {
			return agents.CodexArgs(j.w.cfg.Codex, j.dir, session)
		}
		return agents.CodexArgs(j.w.cfg.Codex, j.dir, "")
	}
	return agents.ClaudeArgs(j.w.cfg.Claude, session, resume)
}

// ---------- QUESTIONS.md fingerprint ----------

type fingerprint struct {
	exists bool
	sha    string
	size   int64
}

func fileFingerprint(path string) fingerprint {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fingerprint{}
	}
	h := sha256Sum(raw)
	return fingerprint{exists: true, sha: h, size: int64(len(raw))}
}

// questionText returns the trimmed question when QUESTIONS.md was created or
// changed during the stage.
func questionText(path string, before fingerprint) string {
	after := fileFingerprint(path)
	if !after.exists {
		return ""
	}
	if before.exists && before.sha == after.sha {
		return ""
	}
	return readFileTrimmed(path, 10000)
}
