// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const adminJobs = `-- name: AdminJobs :many
SELECT id, user_id, title, prompt, status, stage, current_version, pending_revision, needs_attention, worker_id, lease_epoch, lease_expires_at, cancel_requested, attempt, question, state, error, created_at, updated_at, finished_at FROM jobs
WHERE (?1 IS NULL OR status = ?1)
  AND (?2 = 0 OR needs_attention = 1)
  AND (?3 IS NULL OR title LIKE ?3 OR user_id IN (
        SELECT id FROM users WHERE email LIKE ?3 OR name LIKE ?3))
ORDER BY created_at DESC
`

type AdminJobsParams struct {
	Status    interface{}
	Attention interface{}
	Query     interface{}
}

func (q *Queries) AdminJobs(ctx context.Context, arg AdminJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, adminJobs, arg.Status, arg.Attention, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Prompt,
			&i.Status,
			&i.Stage,
			&i.CurrentVersion,
			&i.PendingRevision,
			&i.NeedsAttention,
			&i.WorkerID,
			&i.LeaseEpoch,
			&i.LeaseExpiresAt,
			&i.CancelRequested,
			&i.Attempt,
			&i.Question,
			&i.State,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentRunByID = `-- name: AgentRunByID :one
SELECT id, job_id, version, agent, stage, attempt, session_id, started_at, finished_at, exit_code, outcome, input_tokens, output_tokens, cost_usd, raw_log_key, error FROM agent_runs WHERE id = ? AND job_id = ?
`

type AgentRunByIDParams struct {
	ID    string
	JobID string
}

func (q *Queries) AgentRunByID(ctx context.Context, arg AgentRunByIDParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, agentRunByID, arg.ID, arg.JobID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Agent,
		&i.Stage,
		&i.Attempt,
		&i.SessionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.Outcome,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.RawLogKey,
		&i.Error,
	)
	return i, err
}

const agentRunsByJob = `-- name: AgentRunsByJob :many
SELECT id, job_id, version, agent, stage, attempt, session_id, started_at, finished_at, exit_code, outcome, input_tokens, output_tokens, cost_usd, raw_log_key, error FROM agent_runs WHERE job_id = ? ORDER BY started_at
`

func (q *Queries) AgentRunsByJob(ctx context.Context, jobID string) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, agentRunsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Version,
			&i.Agent,
			&i.Stage,
			&i.Attempt,
			&i.SessionID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ExitCode,
			&i.Outcome,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.RawLogKey,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLoginAttempts = `-- name: CountLoginAttempts :one
SELECT COUNT(*) FROM login_attempts WHERE key = ? AND at > ?
`

type CountLoginAttemptsParams struct {
	Key string
	At  int64
}

func (q *Queries) CountLoginAttempts(ctx context.Context, arg CountLoginAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoginAttempts, arg.Key, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserJobs = `-- name: CountUserJobs :many
SELECT u.id AS user_id, COUNT(j.id) AS jobs_total, MAX(j.created_at) AS last_job_at
FROM users u
LEFT JOIN jobs j ON j.user_id = u.id
WHERE u.role = 'client'
GROUP BY u.id
`

type CountUserJobsRow struct {
	UserID    string
	JobsTotal int64
	LastJobAt interface{}
}

func (q *Queries) CountUserJobs(ctx context.Context) ([]CountUserJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, countUserJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUserJobsRow{}
	for rows.Next() {
		var i CountUserJobsRow
		if err := rows.Scan(&i.UserID, &i.JobsTotal, &i.LastJobAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (id, job_id, version, agent, stage, attempt, session_id,
                        started_at, finished_at, exit_code, outcome, input_tokens,
                        output_tokens, cost_usd, raw_log_key, error)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, job_id, version, agent, stage, attempt, session_id, started_at, finished_at, exit_code, outcome, input_tokens, output_tokens, cost_usd, raw_log_key, error
`

type CreateAgentRunParams struct {
	ID           string
	JobID        string
	Version      int64
	Agent        string
	Stage        string
	Attempt      int64
	SessionID    sql.NullString
	StartedAt    int64
	FinishedAt   sql.NullInt64
	ExitCode     sql.NullInt64
	Outcome      sql.NullString
	InputTokens  int64
	OutputTokens int64
	CostUsd      float64
	RawLogKey    sql.NullString
	Error        sql.NullString
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, createAgentRun,
		arg.ID,
		arg.JobID,
		arg.Version,
		arg.Agent,
		arg.Stage,
		arg.Attempt,
		arg.SessionID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ExitCode,
		arg.Outcome,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.RawLogKey,
		arg.Error,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Agent,
		&i.Stage,
		&i.Attempt,
		&i.SessionID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ExitCode,
		&i.Outcome,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.RawLogKey,
		&i.Error,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, job_id, snapshot, version, idx, title, kind, file_path,
                       preview_path, page_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, job_id, snapshot, version, idx, title, kind, file_path, preview_path, page_count
`

type CreateDocumentParams struct {
	ID          string
	JobID       string
	Snapshot    string
	Version     int64
	Idx         int64
	Title       string
	Kind        string
	FilePath    string
	PreviewPath sql.NullString
	PageCount   int64
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.JobID,
		arg.Snapshot,
		arg.Version,
		arg.Idx,
		arg.Title,
		arg.Kind,
		arg.FilePath,
		arg.PreviewPath,
		arg.PageCount,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Snapshot,
		&i.Version,
		&i.Idx,
		&i.Title,
		&i.Kind,
		&i.FilePath,
		&i.PreviewPath,
		&i.PageCount,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, job_id, ts, kind, visible_to_client, data)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, job_id, ts, kind, visible_to_client, data
`

type CreateEventParams struct {
	ID              string
	JobID           string
	Ts              int64
	Kind            string
	VisibleToClient int64
	Data            string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.ID,
		arg.JobID,
		arg.Ts,
		arg.Kind,
		arg.VisibleToClient,
		arg.Data,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Ts,
		&i.Kind,
		&i.VisibleToClient,
		&i.Data,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, job_id, kind, version, path, blob_key, size, sha256, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, job_id, kind, version, path, blob_key, size, sha256, created_at
`

type CreateFileParams struct {
	ID        string
	JobID     string
	Kind      string
	Version   int64
	Path      string
	BlobKey   string
	Size      int64
	Sha256    string
	CreatedAt int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.Version,
		arg.Path,
		arg.BlobKey,
		arg.Size,
		arg.Sha256,
		arg.CreatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Version,
		&i.Path,
		&i.BlobKey,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, user_id, title, prompt, status, stage, current_version,
                  pending_revision, needs_attention, worker_id, lease_epoch,
                  lease_expires_at, cancel_requested, attempt, question, state,
                  error, created_at, updated_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, title, prompt, status, stage, current_version, pending_revision, needs_attention, worker_id, lease_epoch, lease_expires_at, cancel_requested, attempt, question, state, error, created_at, updated_at, finished_at
`

type CreateJobParams struct {
	ID              string
	UserID          string
	Title           string
	Prompt          string
	Status          string
	Stage           sql.NullString
	CurrentVersion  int64
	PendingRevision sql.NullInt64
	NeedsAttention  int64
	WorkerID        sql.NullString
	LeaseEpoch      int64
	LeaseExpiresAt  sql.NullInt64
	CancelRequested int64
	Attempt         int64
	Question        sql.NullString
	State           string
	Error           sql.NullString
	CreatedAt       int64
	UpdatedAt       int64
	FinishedAt      sql.NullInt64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Prompt,
		arg.Status,
		arg.Stage,
		arg.CurrentVersion,
		arg.PendingRevision,
		arg.NeedsAttention,
		arg.WorkerID,
		arg.LeaseEpoch,
		arg.LeaseExpiresAt,
		arg.CancelRequested,
		arg.Attempt,
		arg.Question,
		arg.State,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FinishedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Prompt,
		&i.Status,
		&i.Stage,
		&i.CurrentVersion,
		&i.PendingRevision,
		&i.NeedsAttention,
		&i.WorkerID,
		&i.LeaseEpoch,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.Attempt,
		&i.Question,
		&i.State,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createLoginAttempt = `-- name: CreateLoginAttempt :exec
INSERT INTO login_attempts (key, at) VALUES (?, ?)
`

type CreateLoginAttemptParams struct {
	Key string
	At  int64
}

func (q *Queries) CreateLoginAttempt(ctx context.Context, arg CreateLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, createLoginAttempt, arg.Key, arg.At)
	return err
}

const createNote = `-- name: CreateNote :one
INSERT INTO job_notes (id, job_id, author_id, text, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, job_id, author_id, text, created_at
`

type CreateNoteParams struct {
	ID        string
	JobID     string
	AuthorID  string
	Text      string
	CreatedAt int64
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (JobNote, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.ID,
		arg.JobID,
		arg.AuthorID,
		arg.Text,
		arg.CreatedAt,
	)
	var i JobNote
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const createPage = `-- name: CreatePage :exec
INSERT INTO pages (document_id, page, image_key, thumb_key, width, height, changed_boxes)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePageParams struct {
	DocumentID   string
	Page         int64
	ImageKey     string
	ThumbKey     string
	Width        int64
	Height       int64
	ChangedBoxes string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) error {
	_, err := q.db.ExecContext(ctx, createPage,
		arg.DocumentID,
		arg.Page,
		arg.ImageKey,
		arg.ThumbKey,
		arg.Width,
		arg.Height,
		arg.ChangedBoxes,
	)
	return err
}

const createRevision = `-- name: CreateRevision :one
INSERT INTO revisions (id, job_id, version, comment, created_at, completed_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, job_id, version, comment, created_at, completed_at
`

type CreateRevisionParams struct {
	ID          string
	JobID       string
	Version     int64
	Comment     string
	CreatedAt   int64
	CompletedAt sql.NullInt64
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (Revision, error) {
	row := q.db.QueryRowContext(ctx, createRevision,
		arg.ID,
		arg.JobID,
		arg.Version,
		arg.Comment,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Comment,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createRevisionRemark = `-- name: CreateRevisionRemark :one
INSERT INTO revision_remarks (id, revision_id, idx, document_id, page, x, y, w, h, text)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, revision_id, idx, document_id, page, x, y, w, h, text
`

type CreateRevisionRemarkParams struct {
	ID         string
	RevisionID string
	Idx        int64
	DocumentID string
	Page       int64
	X          float64
	Y          float64
	W          float64
	H          float64
	Text       string
}

func (q *Queries) CreateRevisionRemark(ctx context.Context, arg CreateRevisionRemarkParams) (RevisionRemark, error) {
	row := q.db.QueryRowContext(ctx, createRevisionRemark,
		arg.ID,
		arg.RevisionID,
		arg.Idx,
		arg.DocumentID,
		arg.Page,
		arg.X,
		arg.Y,
		arg.W,
		arg.H,
		arg.Text,
	)
	var i RevisionRemark
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.Idx,
		&i.DocumentID,
		&i.Page,
		&i.X,
		&i.Y,
		&i.W,
		&i.H,
		&i.Text,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id_hash, user_id, created_at, expires_at, last_seen_at, user_agent, ip)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	IDHash     string
	UserID     string
	CreatedAt  int64
	ExpiresAt  int64
	LastSeenAt int64
	UserAgent  string
	Ip         string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.IDHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.UserAgent,
		arg.Ip,
	)
	return err
}

const createTraceStep = `-- name: CreateTraceStep :exec
INSERT OR IGNORE INTO trace_steps (agent_run_id, seq, ts, type, summary, payload)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTraceStepParams struct {
	AgentRunID string
	Seq        int64
	Ts         int64
	Type       string
	Summary    string
	Payload    string
}

func (q *Queries) CreateTraceStep(ctx context.Context, arg CreateTraceStepParams) error {
	_, err := q.db.ExecContext(ctx, createTraceStep,
		arg.AgentRunID,
		arg.Seq,
		arg.Ts,
		arg.Type,
		arg.Summary,
		arg.Payload,
	)
	return err
}

const currentJobForWorker = `-- name: CurrentJobForWorker :one
SELECT id FROM jobs WHERE worker_id = ? AND status IN ('running','queued','needs_input')
ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) CurrentJobForWorker(ctx context.Context, workerID sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, currentJobForWorker, workerID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteDocumentsBySnapshot = `-- name: DeleteDocumentsBySnapshot :exec
DELETE FROM documents WHERE job_id = ? AND snapshot = ? AND version = ?
`

type DeleteDocumentsBySnapshotParams struct {
	JobID    string
	Snapshot string
	Version  int64
}

func (q *Queries) DeleteDocumentsBySnapshot(ctx context.Context, arg DeleteDocumentsBySnapshotParams) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentsBySnapshot, arg.JobID, arg.Snapshot, arg.Version)
	return err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFileByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFileByID, id)
	return err
}

const deleteFileByJobKindPath = `-- name: DeleteFileByJobKindPath :exec
DELETE FROM files WHERE job_id = ? AND kind = ? AND path = ?
`

type DeleteFileByJobKindPathParams struct {
	JobID string
	Kind  string
	Path  string
}

func (q *Queries) DeleteFileByJobKindPath(ctx context.Context, arg DeleteFileByJobKindPathParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileByJobKindPath, arg.JobID, arg.Kind, arg.Path)
	return err
}

const deleteLoginAttempts = `-- name: DeleteLoginAttempts :exec
DELETE FROM login_attempts WHERE key = ?
`

func (q *Queries) DeleteLoginAttempts(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteLoginAttempts, key)
	return err
}

const deleteOldLoginAttempts = `-- name: DeleteOldLoginAttempts :exec
DELETE FROM login_attempts WHERE at < ?
`

func (q *Queries) DeleteOldLoginAttempts(ctx context.Context, at int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldLoginAttempts, at)
	return err
}

const deletePagesByDocument = `-- name: DeletePagesByDocument :exec
DELETE FROM pages WHERE document_id = ?
`

func (q *Queries) DeletePagesByDocument(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deletePagesByDocument, documentID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, idHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, idHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const documentByID = `-- name: DocumentByID :one
SELECT id, job_id, snapshot, version, idx, title, kind, file_path, preview_path, page_count FROM documents WHERE id = ?
`

func (q *Queries) DocumentByID(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, documentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Snapshot,
		&i.Version,
		&i.Idx,
		&i.Title,
		&i.Kind,
		&i.FilePath,
		&i.PreviewPath,
		&i.PageCount,
	)
	return i, err
}

const documentsBySnapshot = `-- name: DocumentsBySnapshot :many
SELECT id, job_id, snapshot, version, idx, title, kind, file_path, preview_path, page_count FROM documents WHERE job_id = ? AND snapshot = ? AND version = ? ORDER BY idx
`

type DocumentsBySnapshotParams struct {
	JobID    string
	Snapshot string
	Version  int64
}

func (q *Queries) DocumentsBySnapshot(ctx context.Context, arg DocumentsBySnapshotParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, documentsBySnapshot, arg.JobID, arg.Snapshot, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Snapshot,
			&i.Version,
			&i.Idx,
			&i.Title,
			&i.Kind,
			&i.FilePath,
			&i.PreviewPath,
			&i.PageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventsByJob = `-- name: EventsByJob :many
SELECT id, job_id, ts, kind, visible_to_client, data FROM events WHERE job_id = ? ORDER BY ts
`

func (q *Queries) EventsByJob(ctx context.Context, jobID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, eventsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Ts,
			&i.Kind,
			&i.VisibleToClient,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fileByBlobKey = `-- name: FileByBlobKey :one
SELECT id, job_id, kind, version, path, blob_key, size, sha256, created_at FROM files WHERE blob_key = ?
`

func (q *Queries) FileByBlobKey(ctx context.Context, blobKey string) (File, error) {
	row := q.db.QueryRowContext(ctx, fileByBlobKey, blobKey)
	var i File
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Version,
		&i.Path,
		&i.BlobKey,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const fileByJobKindPath = `-- name: FileByJobKindPath :one
SELECT id, job_id, kind, version, path, blob_key, size, sha256, created_at FROM files WHERE job_id = ? AND kind = ? AND path = ?
`

type FileByJobKindPathParams struct {
	JobID string
	Kind  string
	Path  string
}

func (q *Queries) FileByJobKindPath(ctx context.Context, arg FileByJobKindPathParams) (File, error) {
	row := q.db.QueryRowContext(ctx, fileByJobKindPath, arg.JobID, arg.Kind, arg.Path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.Version,
		&i.Path,
		&i.BlobKey,
		&i.Size,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const filesByJob = `-- name: FilesByJob :many
SELECT id, job_id, kind, version, path, blob_key, size, sha256, created_at FROM files WHERE job_id = ? ORDER BY created_at
`

func (q *Queries) FilesByJob(ctx context.Context, jobID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, filesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Kind,
			&i.Version,
			&i.Path,
			&i.BlobKey,
			&i.Size,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filesByJobKind = `-- name: FilesByJobKind :many
SELECT id, job_id, kind, version, path, blob_key, size, sha256, created_at FROM files WHERE job_id = ? AND kind = ? ORDER BY version, path
`

type FilesByJobKindParams struct {
	JobID string
	Kind  string
}

func (q *Queries) FilesByJobKind(ctx context.Context, arg FilesByJobKindParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, filesByJobKind, arg.JobID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Kind,
			&i.Version,
			&i.Path,
			&i.BlobKey,
			&i.Size,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobByID = `-- name: JobByID :one
SELECT id, user_id, title, prompt, status, stage, current_version, pending_revision, needs_attention, worker_id, lease_epoch, lease_expires_at, cancel_requested, attempt, question, state, error, created_at, updated_at, finished_at FROM jobs WHERE id = ?
`

func (q *Queries) JobByID(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, jobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Prompt,
		&i.Status,
		&i.Stage,
		&i.CurrentVersion,
		&i.PendingRevision,
		&i.NeedsAttention,
		&i.WorkerID,
		&i.LeaseEpoch,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.Attempt,
		&i.Question,
		&i.State,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const jobByIDForUser = `-- name: JobByIDForUser :one
SELECT id, user_id, title, prompt, status, stage, current_version, pending_revision, needs_attention, worker_id, lease_epoch, lease_expires_at, cancel_requested, attempt, question, state, error, created_at, updated_at, finished_at FROM jobs WHERE id = ? AND user_id = ?
`

type JobByIDForUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) JobByIDForUser(ctx context.Context, arg JobByIDForUserParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, jobByIDForUser, arg.ID, arg.UserID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Prompt,
		&i.Status,
		&i.Stage,
		&i.CurrentVersion,
		&i.PendingRevision,
		&i.NeedsAttention,
		&i.WorkerID,
		&i.LeaseEpoch,
		&i.LeaseExpiresAt,
		&i.CancelRequested,
		&i.Attempt,
		&i.Question,
		&i.State,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const jobsByUser = `-- name: JobsByUser :many
SELECT id, user_id, title, prompt, status, stage, current_version, pending_revision, needs_attention, worker_id, lease_epoch, lease_expires_at, cancel_requested, attempt, question, state, error, created_at, updated_at, finished_at FROM jobs WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) JobsByUser(ctx context.Context, userID string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, jobsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Prompt,
			&i.Status,
			&i.Stage,
			&i.CurrentVersion,
			&i.PendingRevision,
			&i.NeedsAttention,
			&i.WorkerID,
			&i.LeaseEpoch,
			&i.LeaseExpiresAt,
			&i.CancelRequested,
			&i.Attempt,
			&i.Question,
			&i.State,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobsByWorker = `-- name: JobsByWorker :many
SELECT id, user_id, title, prompt, status, stage, current_version, pending_revision, needs_attention, worker_id, lease_epoch, lease_expires_at, cancel_requested, attempt, question, state, error, created_at, updated_at, finished_at FROM jobs WHERE worker_id = ? AND status = 'running'
`

func (q *Queries) JobsByWorker(ctx context.Context, workerID sql.NullString) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, jobsByWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Prompt,
			&i.Status,
			&i.Stage,
			&i.CurrentVersion,
			&i.PendingRevision,
			&i.NeedsAttention,
			&i.WorkerID,
			&i.LeaseEpoch,
			&i.LeaseExpiresAt,
			&i.CancelRequested,
			&i.Attempt,
			&i.Question,
			&i.State,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT id, email, name FROM users WHERE role = 'client' ORDER BY created_at
`

type ListClientsRow struct {
	ID    string
	Email string
	Name  string
}

func (q *Queries) ListClients(ctx context.Context) ([]ListClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, token_hash, capabilities, info, created_at, last_seen_at FROM workers ORDER BY name
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.Capabilities,
			&i.Info,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notesByJob = `-- name: NotesByJob :many
SELECT id, job_id, author_id, text, created_at FROM job_notes WHERE job_id = ? ORDER BY created_at
`

func (q *Queries) NotesByJob(ctx context.Context, jobID string) ([]JobNote, error) {
	rows, err := q.db.QueryContext(ctx, notesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobNote{}
	for rows.Next() {
		var i JobNote
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pagesByDocument = `-- name: PagesByDocument :many
SELECT document_id, page, image_key, thumb_key, width, height, changed_boxes FROM pages WHERE document_id = ? ORDER BY page
`

func (q *Queries) PagesByDocument(ctx context.Context, documentID string) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, pagesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.DocumentID,
			&i.Page,
			&i.ImageKey,
			&i.ThumbKey,
			&i.Width,
			&i.Height,
			&i.ChangedBoxes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchAgentRun = `-- name: PatchAgentRun :exec
UPDATE agent_runs SET
  session_id = COALESCE(?3, session_id),
  finished_at = COALESCE(?4, finished_at),
  exit_code = COALESCE(?5, exit_code),
  outcome = COALESCE(?6, outcome),
  input_tokens = COALESCE(?7, input_tokens),
  output_tokens = COALESCE(?8, output_tokens),
  cost_usd = COALESCE(?9, cost_usd),
  error = COALESCE(?10, error)
WHERE id = ? AND job_id = ?
`

type PatchAgentRunParams struct {
	SessionID    sql.NullString
	FinishedAt   sql.NullInt64
	ExitCode     sql.NullInt64
	Outcome      sql.NullString
	InputTokens  sql.NullInt64
	OutputTokens sql.NullInt64
	CostUsd      sql.NullFloat64
	Error        sql.NullString
	ID           string
	JobID        string
}

func (q *Queries) PatchAgentRun(ctx context.Context, arg PatchAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, patchAgentRun,
		arg.SessionID,
		arg.FinishedAt,
		arg.ExitCode,
		arg.Outcome,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.Error,
		arg.ID,
		arg.JobID,
	)
	return err
}

const remarksByRevision = `-- name: RemarksByRevision :many
SELECT id, revision_id, idx, document_id, page, x, y, w, h, text FROM revision_remarks WHERE revision_id = ? ORDER BY idx
`

func (q *Queries) RemarksByRevision(ctx context.Context, revisionID string) ([]RevisionRemark, error) {
	rows, err := q.db.QueryContext(ctx, remarksByRevision, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevisionRemark{}
	for rows.Next() {
		var i RevisionRemark
		if err := rows.Scan(
			&i.ID,
			&i.RevisionID,
			&i.Idx,
			&i.DocumentID,
			&i.Page,
			&i.X,
			&i.Y,
			&i.W,
			&i.H,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revisionByJobVersion = `-- name: RevisionByJobVersion :one
SELECT id, job_id, version, comment, created_at, completed_at FROM revisions WHERE job_id = ? AND version = ?
`

type RevisionByJobVersionParams struct {
	JobID   string
	Version int64
}

func (q *Queries) RevisionByJobVersion(ctx context.Context, arg RevisionByJobVersionParams) (Revision, error) {
	row := q.db.QueryRowContext(ctx, revisionByJobVersion, arg.JobID, arg.Version)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Version,
		&i.Comment,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const revisionsByJob = `-- name: RevisionsByJob :many
SELECT id, job_id, version, comment, created_at, completed_at FROM revisions WHERE job_id = ? ORDER BY version
`

func (q *Queries) RevisionsByJob(ctx context.Context, jobID string) ([]Revision, error) {
	rows, err := q.db.QueryContext(ctx, revisionsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Revision{}
	for rows.Next() {
		var i Revision
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Version,
			&i.Comment,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRawLogKey = `-- name: SaveRawLogKey :exec
UPDATE agent_runs SET raw_log_key = ? WHERE id = ? AND job_id = ?
`

type SaveRawLogKeyParams struct {
	RawLogKey sql.NullString
	ID        string
	JobID     string
}

func (q *Queries) SaveRawLogKey(ctx context.Context, arg SaveRawLogKeyParams) error {
	_, err := q.db.ExecContext(ctx, saveRawLogKey, arg.RawLogKey, arg.ID, arg.JobID)
	return err
}

const sessionByIDHash = `-- name: SessionByIDHash :one
SELECT id_hash, user_id, created_at, expires_at, last_seen_at, user_agent, ip FROM sessions WHERE id_hash = ?
`

func (q *Queries) SessionByIDHash(ctx context.Context, idHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, sessionByIDHash, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const sumInputBytes = `-- name: SumInputBytes :one
SELECT COALESCE(SUM(size), 0) FROM files WHERE job_id = ? AND kind = 'input'
`

func (q *Queries) SumInputBytes(ctx context.Context, jobID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumInputBytes, jobID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE id_hash = ?
`

type TouchSessionParams struct {
	LastSeenAt int64
	IDHash     string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.IDHash)
	return err
}

const touchWorker = `-- name: TouchWorker :exec
UPDATE workers SET last_seen_at = ? WHERE id = ?
`

type TouchWorkerParams struct {
	LastSeenAt sql.NullInt64
	ID         string
}

func (q *Queries) TouchWorker(ctx context.Context, arg TouchWorkerParams) error {
	_, err := q.db.ExecContext(ctx, touchWorker, arg.LastSeenAt, arg.ID)
	return err
}

const traceStepsByRun = `-- name: TraceStepsByRun :many
SELECT agent_run_id, seq, ts, type, summary, payload FROM trace_steps WHERE agent_run_id = ? AND seq > ? ORDER BY seq LIMIT ?
`

type TraceStepsByRunParams struct {
	AgentRunID string
	Seq        int64
	Limit      int64
}

func (q *Queries) TraceStepsByRun(ctx context.Context, arg TraceStepsByRunParams) ([]TraceStep, error) {
	rows, err := q.db.QueryContext(ctx, traceStepsByRun, arg.AgentRunID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TraceStep{}
	for rows.Next() {
		var i TraceStep
		if err := rows.Scan(
			&i.AgentRunID,
			&i.Seq,
			&i.Ts,
			&i.Type,
			&i.Summary,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobAnswer = `-- name: UpdateJobAnswer :exec
UPDATE jobs
SET status = 'queued', question = NULL, state = ?, pending_revision = NULL,
    updated_at = ?
WHERE id = ?
`

type UpdateJobAnswerParams struct {
	State     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateJobAnswer(ctx context.Context, arg UpdateJobAnswerParams) error {
	_, err := q.db.ExecContext(ctx, updateJobAnswer, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const updateJobAttention = `-- name: UpdateJobAttention :exec
UPDATE jobs SET needs_attention = ?, updated_at = ? WHERE id = ?
`

type UpdateJobAttentionParams struct {
	NeedsAttention int64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) UpdateJobAttention(ctx context.Context, arg UpdateJobAttentionParams) error {
	_, err := q.db.ExecContext(ctx, updateJobAttention, arg.NeedsAttention, arg.UpdatedAt, arg.ID)
	return err
}

const updateJobCancelRequested = `-- name: UpdateJobCancelRequested :exec
UPDATE jobs SET cancel_requested = 1, updated_at = ? WHERE id = ?
`

type UpdateJobCancelRequestedParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateJobCancelRequested(ctx context.Context, arg UpdateJobCancelRequestedParams) error {
	_, err := q.db.ExecContext(ctx, updateJobCancelRequested, arg.UpdatedAt, arg.ID)
	return err
}

const updateJobState = `-- name: UpdateJobState :exec
UPDATE jobs SET state = ?, updated_at = ? WHERE id = ?
`

type UpdateJobStateParams struct {
	State     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateJobState(ctx context.Context, arg UpdateJobStateParams) error {
	_, err := q.db.ExecContext(ctx, updateJobState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = ?, stage = ?, current_version = ?, pending_revision = ?,
    needs_attention = ?, attempt = ?, question = ?, error = ?,
    cancel_requested = ?, updated_at = ?, finished_at = ?
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status          string
	Stage           sql.NullString
	CurrentVersion  int64
	PendingRevision sql.NullInt64
	NeedsAttention  int64
	Attempt         int64
	Question        sql.NullString
	Error           sql.NullString
	CancelRequested int64
	UpdatedAt       int64
	FinishedAt      sql.NullInt64
	ID              string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus,
		arg.Status,
		arg.Stage,
		arg.CurrentVersion,
		arg.PendingRevision,
		arg.NeedsAttention,
		arg.Attempt,
		arg.Question,
		arg.Error,
		arg.CancelRequested,
		arg.UpdatedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const updateJobTitle = `-- name: UpdateJobTitle :exec
UPDATE jobs SET title = ?, updated_at = ? WHERE id = ?
`

type UpdateJobTitleParams struct {
	Title     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateJobTitle(ctx context.Context, arg UpdateJobTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateJobTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}

const workerByID = `-- name: WorkerByID :one
SELECT id, name, token_hash, capabilities, info, created_at, last_seen_at FROM workers WHERE id = ?
`

func (q *Queries) WorkerByID(ctx context.Context, id string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, workerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Capabilities,
		&i.Info,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const workerByTokenHash = `-- name: WorkerByTokenHash :one
SELECT id, name, token_hash, capabilities, info, created_at, last_seen_at FROM workers WHERE token_hash = ?
`

func (q *Queries) WorkerByTokenHash(ctx context.Context, tokenHash string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, workerByTokenHash, tokenHash)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Capabilities,
		&i.Info,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
