// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type AgentRun struct {
	ID           string
	JobID        string
	Version      int64
	Agent        string
	Stage        string
	Attempt      int64
	SessionID    sql.NullString
	StartedAt    int64
	FinishedAt   sql.NullInt64
	ExitCode     sql.NullInt64
	Outcome      sql.NullString
	InputTokens  int64
	OutputTokens int64
	CostUsd      float64
	RawLogKey    sql.NullString
	Error        sql.NullString
}

type Document struct {
	ID          string
	JobID       string
	Snapshot    string
	Version     int64
	Idx         int64
	Title       string
	Kind        string
	FilePath    string
	PreviewPath sql.NullString
	PageCount   int64
}

type Event struct {
	ID              string
	JobID           string
	Ts              int64
	Kind            string
	VisibleToClient int64
	Data            string
}

type File struct {
	ID        string
	JobID     string
	Kind      string
	Version   int64
	Path      string
	BlobKey   string
	Size      int64
	Sha256    string
	CreatedAt int64
}

type Job struct {
	ID              string
	UserID          string
	Title           string
	Prompt          string
	Status          string
	Stage           sql.NullString
	CurrentVersion  int64
	PendingRevision sql.NullInt64
	NeedsAttention  int64
	WorkerID        sql.NullString
	LeaseEpoch      int64
	LeaseExpiresAt  sql.NullInt64
	CancelRequested int64
	Attempt         int64
	Question        sql.NullString
	State           string
	Error           sql.NullString
	CreatedAt       int64
	UpdatedAt       int64
	FinishedAt      sql.NullInt64
	StageStartedAt  sql.NullInt64
}

type JobNote struct {
	ID        string
	JobID     string
	AuthorID  string
	Text      string
	CreatedAt int64
}

type LoginAttempt struct {
	Key string
	At  int64
}

type Page struct {
	DocumentID   string
	Page         int64
	ImageKey     string
	ThumbKey     string
	Width        int64
	Height       int64
	ChangedBoxes string
}

type Revision struct {
	ID          string
	JobID       string
	Version     int64
	Comment     string
	CreatedAt   int64
	CompletedAt sql.NullInt64
}

type RevisionRemark struct {
	ID         string
	RevisionID string
	Idx        int64
	DocumentID string
	Page       int64
	X          float64
	Y          float64
	W          float64
	H          float64
	Text       string
}

type Session struct {
	IDHash     string
	UserID     string
	CreatedAt  int64
	ExpiresAt  int64
	LastSeenAt int64
	UserAgent  string
	Ip         string
}

type TraceStep struct {
	AgentRunID string
	Seq        int64
	Ts         int64
	Type       string
	Summary    string
	Payload    string
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string
	Name         string
	CreatedAt    int64
	DisabledAt   sql.NullInt64
}

type Worker struct {
	ID           string
	Name         string
	TokenHash    string
	Capabilities string
	Info         string
	CreatedAt    int64
	LastSeenAt   sql.NullInt64
}
