// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, role, name, created_at, disabled_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, email, password_hash, role, name, created_at, disabled_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string
	Name         string
	CreatedAt    int64
	DisabledAt   sql.NullInt64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
		arg.CreatedAt,
		arg.DisabledAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (id, name, token_hash, capabilities, info, created_at, last_seen_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, token_hash, capabilities, info, created_at, last_seen_at
`

type CreateWorkerParams struct {
	ID           string
	Name         string
	TokenHash    string
	Capabilities string
	Info         string
	CreatedAt    int64
	LastSeenAt   sql.NullInt64
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.Capabilities,
		arg.Info,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Capabilities,
		&i.Info,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, password_hash, role, name, created_at, disabled_at FROM users WHERE email = ? COLLATE NOCASE
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, password_hash, role, name, created_at, disabled_at FROM users WHERE id = ?
`

func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const workerByName = `-- name: WorkerByName :one
SELECT id, name, token_hash, capabilities, info, created_at, last_seen_at FROM workers WHERE name = ?
`

func (q *Queries) WorkerByName(ctx context.Context, name string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, workerByName, name)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Capabilities,
		&i.Info,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
