/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход по email и паролю */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список заказов клиента */
        get: operations["clientListJobs"];
        put?: never;
        /** Создать заказ */
        post: operations["clientCreateJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Карточка заказа */
        get: operations["clientGetJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/input": {
        parameters: {
            query: {
                path: components["parameters"]["InputPath"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Загрузить файл (только uploading) */
        put: operations["clientUploadInput"];
        post?: never;
        /** Удалить загруженный файл (только uploading) */
        delete: operations["clientDeleteInput"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить заказ (uploading -> queued) */
        post: operations["clientSubmitJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ответить на вопрос агента */
        post: operations["clientAnswerJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить заказ */
        post: operations["clientCancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить на доработку (multipart) */
        post: operations["clientCreateRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/versions/{v}/documents/{document_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        /** Страницы документа версии */
        get: operations["clientListVersionPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/versions/{v}/pages/{document_id}/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                document_id: components["parameters"]["DocumentId"];
                page: components["parameters"]["PageNumber"];
            };
            cookie?: never;
        };
        /** Картинка страницы */
        get: operations["clientGetVersionPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/versions/{v}/thumbs/{document_id}/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                document_id: components["parameters"]["DocumentId"];
                page: components["parameters"]["PageNumber"];
            };
            cookie?: never;
        };
        /** Мини-копия страницы */
        get: operations["clientGetVersionThumb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/versions/{v}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                /** @description Путь файла в комплекте */
                path: string;
            };
            cookie?: never;
        };
        /** Скачать файл комплекта */
        get: operations["clientGetVersionFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/versions/{v}/bundle.zip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        /** Архив комплекта версии */
        get: operations["clientGetVersionBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/jobs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** SSE-поток заказа */
        get: operations["clientJobStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список заказов */
        get: operations["adminListJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Карточка заказа */
        get: operations["adminGetJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/runs/{run_id}/steps": {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        /** Шаги запуска агента */
        get: operations["adminGetRunSteps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/runs/{run_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        /** Сырой JSONL лог агента */
        get: operations["adminGetRunLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ответить за клиента */
        post: operations["adminAnswerJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Повторить failed заказ */
        post: operations["adminRetryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить заказ */
        post: operations["adminCancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/attention": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Снять флаг внимания */
        post: operations["adminSetAttention"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить заметку */
        post: operations["adminCreateNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** SSE-поток заказа для пульта */
        get: operations["adminJobStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список воркеров */
        get: operations["adminListWorkers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список клиентов */
        get: operations["adminListClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Регистрация воркера */
        post: operations["workerRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Забрать заказ (long-poll до 25 с) */
        post: operations["workerClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Продлить lease */
        post: operations["workerHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/input": {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Список входных файлов */
        get: operations["workerListInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/input/{path}": {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                path: string;
            };
            cookie?: never;
        };
        /** Скачать входной файл */
        get: operations["workerGetInput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать запуск агента */
        post: operations["workerCreateRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить запуск агента */
        patch: operations["workerPatchRun"];
        trace?: never;
    };
    "/api/worker/jobs/{id}/runs/{run_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отправить пачку шагов трейса */
        post: operations["workerAppendSteps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/runs/{run_id}/log": {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Загрузить сырой лог */
        put: operations["workerPutRunLog"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge состояния заказа */
        post: operations["workerSetState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/snapshot/{snapshot}/files": {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
                path: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
            };
            cookie?: never;
        };
        get?: never;
        /** Загрузить файл снимка */
        put: operations["workerPutSnapshotFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/snapshot/{snapshot}/pages/{document_idx}/{page}": {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
                document_idx: number;
                page: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Загрузить картинку страницы снимка */
        put: operations["workerPutSnapshotPage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/snapshot/{snapshot}/thumbs/{document_idx}/{page}": {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
                document_idx: number;
                page: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Загрузить мини-копию страницы снимка */
        put: operations["workerPutSnapshotThumb"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/input/revision/{n}/remarks/{idx}": {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                n: number;
                idx: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Загрузить вырезку замечания */
        put: operations["workerPutRevisionRemark"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/snapshot/{snapshot}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Зафиксировать снимок */
        post: operations["workerCommitSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/question": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Задать вопрос клиенту */
        post: operations["workerQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worker/jobs/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить заказ */
        post: operations["workerFinish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        User: {
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "client" | "admin";
        };
        UserResponse: {
            user: components["schemas"]["User"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        CreateJobRequest: {
            prompt: string;
        };
        AnswerRequest: {
            text: string;
        };
        AttentionRequest: {
            needs_attention: boolean;
        };
        NoteRequest: {
            text: string;
        };
        UploadResult: {
            path: string;
            size: number;
        };
        StatusStep: {
            title: string;
            /** @enum {string} */
            state: "done" | "active" | "pending";
        };
        JobSummary: {
            id: string;
            title: string;
            /** @enum {string} */
            client_status: "uploading" | "accepted" | "in_progress" | "revising" | "needs_input" | "done" | "delayed" | "canceled";
            status_text: string;
            current_version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ClientJobDetail: components["schemas"]["JobSummary"] & {
            prompt: string;
            question?: string;
            status_steps: components["schemas"]["StatusStep"][];
            input_files: components["schemas"]["InputFile"][];
            versions: components["schemas"]["Version"][];
            planned_documents: components["schemas"]["PlannedDocument"][];
            revisions: components["schemas"]["Revision"][];
            can_cancel: boolean;
            can_revise: boolean;
            can_answer: boolean;
        };
        InputFile: {
            path: string;
            size: number;
        };
        PlannedDocument: {
            title: string;
            kind: string;
        };
        Version: {
            version: number;
            /** Format: date-time */
            ready_at: string;
            documents: components["schemas"]["Document"][];
        };
        Document: {
            id: string;
            idx: number;
            title: string;
            kind: string;
            file_path: string;
            size: number;
            page_count: number;
            download_url: string;
        };
        Page: {
            page: number;
            width: number;
            height: number;
            image_url: string;
            thumb_url: string;
            changed_boxes: components["schemas"]["ChangedBox"][];
        };
        ChangedBox: {
            x: number;
            y: number;
            w: number;
            h: number;
        };
        PageList: {
            pages: components["schemas"]["Page"][];
        };
        Revision: {
            version: number;
            comment: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at: string;
            remarks: components["schemas"]["Remark"][];
        };
        Remark: {
            idx: number;
            document_id: string;
            page: number;
            x: number;
            y: number;
            w: number;
            h: number;
            text: string;
        };
        ClientJobList: {
            jobs: components["schemas"]["JobSummary"][];
        };
        ClientRef: {
            id: string;
            email: string;
            name: string;
        };
        AdminJobSummary: {
            id: string;
            title: string;
            client: components["schemas"]["ClientRef"];
            status: string;
            stage?: string;
            client_status: string;
            current_version: number;
            pending_revision?: number;
            needs_attention: boolean;
            attempt: number;
            worker?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminJobDetail: components["schemas"]["AdminJobSummary"] & {
            prompt: string;
            question?: string;
            status_steps: components["schemas"]["StatusStep"][];
            input_files: components["schemas"]["InputFile"][];
            versions: components["schemas"]["Version"][];
            planned_documents: components["schemas"]["PlannedDocument"][];
            revisions: components["schemas"]["Revision"][];
            error: string;
            state: {
                [key: string]: unknown;
            };
            lease_epoch: number;
            /** Format: date-time */
            lease_expires_at?: string;
            draft?: components["schemas"]["DraftSnapshot"];
            verification?: components["schemas"]["Verification"];
            agent_runs: components["schemas"]["AgentRun"][];
            events: components["schemas"]["Event"][];
            notes: components["schemas"]["JobNote"][];
            can_cancel?: boolean;
            can_revise?: boolean;
            can_answer?: boolean;
        };
        DraftSnapshot: {
            documents: components["schemas"]["Document"][];
        };
        Verification: {
            found: number;
            fixed: number;
            remaining: components["schemas"]["VerificationItem"][];
        };
        VerificationItem: {
            severity: string;
            description: string;
        };
        AgentRun: {
            id: string;
            agent: string;
            stage: string;
            version: number;
            attempt: number;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            finished_at?: string;
            outcome?: string;
            input_tokens?: number;
            output_tokens?: number;
            cost_usd?: number;
            error?: string;
        };
        Event: {
            /** Format: date-time */
            ts: string;
            kind: string;
            data: {
                [key: string]: unknown;
            };
        };
        JobNote: {
            id: string;
            author: string;
            text: string;
            /** Format: date-time */
            created_at: string;
        };
        AdminJobList: {
            jobs: components["schemas"]["AdminJobSummary"][];
        };
        WorkerStatus: {
            id: string;
            name: string;
            capabilities: string[];
            info: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            last_seen_at?: string;
            online: boolean;
            current_job?: string;
        };
        WorkerList: components["schemas"]["WorkerStatus"][];
        ClientAccount: {
            id: string;
            email: string;
            name: string;
            jobs_total: number;
            /** Format: date-time */
            last_job_at?: string;
        };
        ClientAccountList: components["schemas"]["ClientAccount"][];
        TraceStep: {
            seq: number;
            /** Format: date-time */
            ts: string;
            type: string;
            summary: string;
            payload: {
                [key: string]: unknown;
            };
        };
        TraceStepList: {
            steps: components["schemas"]["TraceStep"][];
        };
        WorkerRegisterRequest: {
            capabilities: string[];
            info: {
                [key: string]: unknown;
            };
        };
        WorkerRegisterResponse: {
            worker_id: string;
        };
        EpochRequest: {
            epoch: number;
        };
        HeartbeatResponse: {
            /** Format: date-time */
            lease_expires_at: string;
            cancel: boolean;
        };
        WorkerInputFile: {
            path: string;
            size: number;
            sha256: string;
            revision: number;
        };
        WorkerInputFileList: {
            files: components["schemas"]["WorkerInputFile"][];
        };
        Assignment: {
            job_id: string;
            epoch: number;
            /** Format: date-time */
            lease_expires_at: string;
            /** @enum {string} */
            action: "start" | "continue" | "answer" | "revise";
            /** @enum {string} */
            stage: "draft" | "verify" | "revise";
            attempt: number;
            prompt: string;
            version: number;
            state?: {
                [key: string]: unknown;
            };
            answer?: string;
            revision?: components["schemas"]["AssignmentRevision"];
        };
        AssignmentRevision: {
            version: number;
            comment: string;
            remarks: components["schemas"]["AssignmentRemark"][];
            files: components["schemas"]["RevisionFile"][];
        };
        AssignmentRemark: {
            idx: number;
            document_title: string;
            file_path: string;
            page: number;
            x: number;
            y: number;
            w: number;
            h: number;
            text: string;
        };
        RevisionFile: {
            path: string;
        };
        CreateRunRequest: {
            epoch: number;
            /** @enum {string} */
            agent: "codex" | "claude";
            /** @enum {string} */
            stage: "draft" | "verify" | "revise";
            version: number;
            attempt: number;
            session_id?: string;
        };
        CreateRunResponse: {
            run_id: string;
        };
        PatchRunRequest: {
            epoch: number;
            session_id?: string;
            /** Format: date-time */
            finished_at?: string;
            exit_code?: number;
            /** @enum {string} */
            outcome?: "ok" | "question" | "failed" | "canceled" | "timeout";
            input_tokens?: number;
            output_tokens?: number;
            cost_usd?: number;
            error?: string;
        };
        AppendStepsRequest: {
            epoch: number;
            steps: components["schemas"]["NewTraceStep"][];
        };
        NewTraceStep: {
            seq: number;
            /** Format: date-time */
            ts: string;
            type: string;
            summary: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        SetStateRequest: {
            epoch: number;
            state: {
                [key: string]: unknown;
            };
        };
        SnapshotPage: {
            page: number;
            width: number;
            height: number;
            changed_boxes?: components["schemas"]["ChangedBox"][];
        };
        SnapshotDocument: {
            idx: number;
            title: string;
            kind: string;
            file_path: string;
            preview_path?: string;
            page_count: number;
            pages: components["schemas"]["SnapshotPage"][];
        };
        CommitSnapshotRequest: {
            epoch: number;
            title?: string;
            documents: components["schemas"]["SnapshotDocument"][];
            verification?: components["schemas"]["Verification"];
        };
        QuestionRequest: {
            epoch: number;
            text: string;
        };
        FinishRequest: {
            epoch: number;
            /** @enum {string} */
            outcome: "ok" | "failed" | "canceled" | "timeout";
            version?: number;
            error?: string;
        };
    };
    responses: {
        /** @description Неверное тело или параметры */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Нет сессии или неверный токен */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не та роль или не совпал Origin */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Объект не найден или чужой */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Недопустимый переход статуса */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Устаревший lease */
        StaleLease: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Превышен лимит загрузки */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Слишком много попыток входа */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        JobId: string;
        VersionPath: number;
        DocumentId: string;
        PageNumber: string;
        InputPath: string;
        EpochQuery: number;
        Snapshot: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Успешный вход, ставит cookie sl_session */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия удалена, cookie очищена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий пользователь */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    clientListJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказы новые сверху */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientJobList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    clientCreateJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Заказ создан (uploading) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientJobDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    clientGetJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка заказа */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientJobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    clientUploadInput: {
        parameters: {
            query: {
                path: components["parameters"]["InputPath"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Файл загружен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
        };
    };
    clientDeleteInput: {
        parameters: {
            query: {
                path: components["parameters"]["InputPath"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    clientSubmitJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ принят */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientJobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    clientAnswerJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Ответ принят */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientJobDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    clientCancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ отменён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientJobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    clientCreateRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description JSON с комментарием и замечаниями */
                    data: string;
                    files?: string[];
                };
            };
        };
        responses: {
            /** @description Доработка принята */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientJobDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    clientListVersionPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                document_id: components["parameters"]["DocumentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страницы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    clientGetVersionPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                document_id: components["parameters"]["DocumentId"];
                page: components["parameters"]["PageNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG страницы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    clientGetVersionThumb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                document_id: components["parameters"]["DocumentId"];
                page: components["parameters"]["PageNumber"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG мини-копии */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    clientGetVersionFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
                /** @description Путь файла в комплекте */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    clientGetVersionBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                v: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ZIP-архив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    clientJobStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream (snapshot, job, ping) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    adminListJobs: {
        parameters: {
            query?: {
                status?: string;
                attention?: number;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminGetJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка заказа */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminGetRunSteps: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Шаги трейса */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceStepList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminGetRunLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSONL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminAnswerJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Ответ принят */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    adminRetryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ повторён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    adminCancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заказ отменён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    adminSetAttention: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttentionRequest"];
            };
        };
        responses: {
            /** @description Флаг обновлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminCreateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description Заметка создана */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobNote"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminJobStream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream (snapshot, job, steps, ping) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminListWorkers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Воркеры */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminListClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Клиенты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientAccountList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    workerRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerRegisterRequest"];
            };
        };
        responses: {
            /** @description Воркер зарегистрирован */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerRegisterResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    workerClaim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задание */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            /** @description Заказов нет */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    workerHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpochRequest"];
            };
        };
        responses: {
            /** @description Lease продлён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerListInput: {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файлы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerInputFileList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerGetInput: {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerCreateRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Запуск создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerPatchRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRunRequest"];
            };
        };
        responses: {
            /** @description Обновлено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerAppendSteps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppendStepsRequest"];
            };
        };
        responses: {
            /** @description Принято (дубликаты игнорируются) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerPutRunLog: {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerSetState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStateRequest"];
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerPutSnapshotFile: {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
                path: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerPutSnapshotPage: {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
                document_idx: number;
                page: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerPutSnapshotThumb: {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
                document_idx: number;
                page: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerPutRevisionRemark: {
        parameters: {
            query: {
                epoch: components["parameters"]["EpochQuery"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                n: number;
                idx: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerCommitSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
                snapshot: components["parameters"]["Snapshot"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitSnapshotRequest"];
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
    workerFinish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishRequest"];
            };
        };
        responses: {
            /** @description Принято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["StaleLease"];
        };
    };
}
